# regextest_ui.tcl --
#
# UI generated by GUI Builder Build 146 on 2008-10-17 11:11:53 from:
#    /home/tmp/jeff/regextest.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval regextest {}

package require Tk
# regextest::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc regextest::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base
    variable SCRIPTDIR ; # defined in main script


    # Widget Initialization
    variable _frame_string [frame $BASE._frame_string \
	    -container 1 \
	    -padx 5 \
	    -pady 5]
    variable _labelframe_1 [labelframe $BASE._labelframe_1 \
	    -text "Info:"]
    variable _frame_button [frame $BASE._frame_button]
    variable _frame_regex [frame $BASE._frame_regex]
    variable _label_Text [label $BASE._label_Text \
	    -text "Text:"]
    variable _label_Regex [label $BASE._label_Regex \
	    -text "Regex:"]
    variable _button_run [button $BASE._button_run \
	    -command "Run" \
	    -font {helvetica 9 bold} \
	    -text "Run"]
    variable _text_string [text $BASE._text_string \
	    -background "#ffffff" \
	    -font {courier 10} \
	    -height 10 \
	    -xscrollcommand [namespace code [list _text_string_xscrollcommand]] \
	    -yscrollcommand [namespace code [list _text_string_yscrollcommand]]]
    variable _text_info [text $BASE._text_info \
	    -font {courier 10} \
	    -height 20 \
	    -state "disabled" \
	    -width 85 \
	    -xscrollcommand [namespace code [list _text_info_xscrollcommand]] \
	    -yscrollcommand [namespace code [list _text_info_yscrollcommand]]]
    variable _entry_regex [entry $BASE._entry_regex \
	    -background "#ffffff" \
	    -font {courier 10} \
	    -invalidcommand [namespace code [list _entry_regex_invalidcommand]] \
	    -textvariable "regex" \
	    -validatecommand [namespace code [list _entry_regex_validatecommand]] \
	    -width 80 \
	    -xscrollcommand [namespace code [list _entry_regex_xscrollcommand]]]


    # Geometry Management

    grid $BASE._frame_string -in $root -row 1 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._labelframe_1 -in $root -row 4 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._frame_button -in $root -row 3 -column 1 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._frame_regex -in $root -row 2 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._label_Text -in $root -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._label_Regex -in $root -row 2 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._button_run -in $base._frame_button -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky ""
    grid $BASE._text_string -in $base._frame_string -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._text_info -in $base._labelframe_1 -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "news"
    grid $BASE._entry_regex -in $base._frame_regex -row 1 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky "ew"

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 147 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 41 -pad 0
    grid rowconfigure $root 3 -weight 0 -minsize 8 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 303 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 61 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 374 -pad 0
    grid rowconfigure $base._frame_string 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_string 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_button 1 -weight 0 -minsize 33 -pad 0
    grid columnconfigure $base._frame_button 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._frame_regex 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $base._frame_regex 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $base._labelframe_1 1 -weight 0 -minsize 2 -pad 0
    grid columnconfigure $base._labelframe_1 1 -weight 0 -minsize 40 -pad 0
}
